#!/usr/bin/env ruby
#^syntax detection

forge "https://forgeapi.puppetlabs.com"

# mod, <module name>, <version or tag>, <source>
mod 'puppetlabs-ntp'
mod 'puppetlabs-firewall'
#
mod 'saz-timezone'
#
#mod 'razorsedge-cloudera'
#
mod 'cesnet-site_hadoop',
  :git => 'git://github.com/MetaCenterCloudPuppet/cesnet-site_hadoop.git'
mod 'cesnet-hadoop',
  :git => 'git://github.com/MetaCenterCloudPuppet/cesnet-hadoop.git'
mod 'cesnet-zookeeper',
  :git => 'git://github.com/MetaCenterCloudPuppet/cesnet-zookeeper.git'
mod 'cesnet-hbase',
  :git => 'git://github.com/MetaCenterCloudPuppet/cesnet-hbase.git'

